spring.application.name=studentManagement

spring.datasource.url=jdbc:mysql://localhost:3306/learning_springboot
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=mySuperSecretKeyThatIsAtLeast32Chars!